# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170512_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posted',
            new_name='posted_date',
        ),
    ]
