# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170513_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_picture_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
