# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170513_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
