# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
