# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyName', models.CharField(max_length=50)),
                ('propertyDescription', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionId', models.IntegerField(default=0)),
                ('location', models.CharField(default='', max_length=250)),
                ('regionArray', models.CharField(default='', max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('sleeps', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('bedrooms', models.IntegerField(default=0)),
                ('detailPageUrl', models.CharField(max_length=250, unique=True)),
                ('galleryUrl', models.CharField(default='', max_length=250)),
                ('geoCode', models.CharField(default='', max_length=50)),
                ('shortJSON', models.TextField(default='')),
                ('longJSON', models.TextField(default='')),
                ('is_checked', models.BooleanField(default=False)),
                ('slug', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
