# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('sleeps', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('bedrooms', models.IntegerField(default=0)),
                ('detailPageUrl', models.CharField(default='', max_length=250)),
                ('regionPathHierarchy', models.CharField(default='', max_length=250)),
                ('galleryUrl', models.CharField(default='', max_length=250)),
                ('jsonData', models.TextField()),
            ],
        ),
    ]
