# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_delete_relations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.IntegerField(default=0)),
                ('rental_id', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('sleeps', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('bedrooms', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='relations',
            unique_together=set([('rental_id', 'place_id')]),
        ),
    ]
