# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rental_regionid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='regionPathHierarchy',
            new_name='regionArray',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='jsonData',
            new_name='shortJSON',
        ),
        migrations.AddField(
            model_name='rental',
            name='geoCode',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rental',
            name='referer',
            field=models.CharField(default='', max_length=50),
        ),
    ]
