# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_auto_20170216_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='detailPageUrl',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
