# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_auto_20170311_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='slug',
        ),
    ]
