# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_auto_20170303_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='averageRating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='rental',
            name='reviewCount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
