# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_remove_rental_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='picturesArray',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
