# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_auto_20170216_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
