# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_rental_picturesarray'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='title',
            field=models.TextField(default='', max_length=250),
        ),
    ]
