# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_rental_is_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='longJSON',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='rental',
            name='shortJSON',
            field=models.TextField(default=''),
        ),
    ]
