# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_rental_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
    ]
