# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_auto_20170515_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='slug',
            field=models.CharField(default='', max_length=250),
        ),
    ]
