# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='title',
            new_name='meta_title',
        ),
        migrations.AddField(
            model_name='country',
            name='meta_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='page_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
