# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='search_term',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
