# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_auto_20170302_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='city',
        ),
        migrations.RemoveField(
            model_name='district',
            name='country',
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
