# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_auto_20170316_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='search_term',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
