# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_auto_20170316_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
